discord:
  # The bot token acquired from https://discord.com/developers/applications
  token: ""
  # The shards section can be omitted to run in
  # min and max can be omitted to just specify the total shards.
  # If total is not specified, min and max will not take effect and the total will be retrieved from Discord
  shards:
    min: 0
    max: 2
    total: 10

development:
  debugLogging: false # Enables debug logging in the console
  registerCommandsOnBoot: false # Registers the commands with Discord on boot

database:
  url: "postgresql://localhost:5432/"
  username: "postgres"
  password: ""

# This config section can be omitted if RabbitMQ is not being used
rabbitMQ:
  username: "user"
  password: "password"
  hostname: "localhost"
  port: 5672
  virtualHost: "/"
  # OR
  url: "amqp://user:password@host:5672"

values:
  maxComponentsCachedPerChannel: 50

dashboard:
  baseUrl: "http://localhost:3000"
  encryption:
    # A public/private key pair will be generated. The keys will be written to generated.pem (Private key)
    # and generated.pub (Public key)
    generate: true
    # OR
    privateKeyFile: dashboard_login.pem # Path to an ECC 256-bit PKCS#8 formatted private key
    publicKeyFile: dashboard_login.pub # Path to an ECC 256-bit X.509 formatted public keym